### ISSUE TITLE
How would you compile this yourself?

### ISSUE THREAD

**Issue by mrbot-king** [cyph/sidh.js#2]
I have tried to compile this but I keep getting into issues with unreachable executed. Could you maybe tell me how you compiled your code.

**Comment by trpapp** [comment]
Were you able to include the P503_api (microsoft/PQCrypto-SIDH) and sodium (jedisct1/libsodium) headers?

**Comment by mrbot-king** [comment]
> Were you able to include the P503_api (microsoft/PQCrypto-SIDH) and sodium (jedisct1/libsodium) headers?

Yes I have includes those, the error is cat dist/sidh.asm.js >> dist/sidh.tmp.js cat: dist/sidh.asm.js: No such file or directory. I wanna say that emscipten removed asm so that might be the problem

**Comment by buu700** [comment]
Sorry about the late reply! I did a little bit of housecleaning that should make this easier:

```
git clone https://github.com/cyph/pqcrypto.js
cd pqcrypto.js
./configure
cd packages/sidh
make
```

If that doesn't fully solve the problem or you run into any other issues, feel free to open a new issue at https://github.com/cyph/pqcrypto.js.
